//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/LRIT.ASP.Data")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ASPTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double COGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSPTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DCTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayTimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceSinceLastReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMONumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyValueWeatherInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LRITMessageIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeWGS84Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeWGS84Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SODField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SOGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TerminalTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ASPTimeStamp {
            get {
                return this.ASPTimeStampField;
            }
            set {
                if ((this.ASPTimeStampField.Equals(value) != true)) {
                    this.ASPTimeStampField = value;
                    this.RaisePropertyChanged("ASPTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double COG {
            get {
                return this.COGField;
            }
            set {
                if ((this.COGField.Equals(value) != true)) {
                    this.COGField = value;
                    this.RaisePropertyChanged("COG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSPTimeStamp {
            get {
                return this.CSPTimeStampField;
            }
            set {
                if ((this.CSPTimeStampField.Equals(value) != true)) {
                    this.CSPTimeStampField = value;
                    this.RaisePropertyChanged("CSPTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DCTimeStamp {
            get {
                return this.DCTimeStampField;
            }
            set {
                if ((this.DCTimeStampField.Equals(value) != true)) {
                    this.DCTimeStampField = value;
                    this.RaisePropertyChanged("DCTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayTimeZone {
            get {
                return this.DisplayTimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayTimeZoneField, value) != true)) {
                    this.DisplayTimeZoneField = value;
                    this.RaisePropertyChanged("DisplayTimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DistanceSinceLastReport {
            get {
                return this.DistanceSinceLastReportField;
            }
            set {
                if ((this.DistanceSinceLastReportField.Equals(value) != true)) {
                    this.DistanceSinceLastReportField = value;
                    this.RaisePropertyChanged("DistanceSinceLastReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMONum {
            get {
                return this.IMONumField;
            }
            set {
                if ((object.ReferenceEquals(this.IMONumField, value) != true)) {
                    this.IMONumField = value;
                    this.RaisePropertyChanged("IMONum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyValueWeatherInfo {
            get {
                return this.KeyValueWeatherInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyValueWeatherInfoField, value) != true)) {
                    this.KeyValueWeatherInfoField = value;
                    this.RaisePropertyChanged("KeyValueWeatherInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LRITMessageIds {
            get {
                return this.LRITMessageIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.LRITMessageIdsField, value) != true)) {
                    this.LRITMessageIdsField = value;
                    this.RaisePropertyChanged("LRITMessageIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatitudeWGS84 {
            get {
                return this.LatitudeWGS84Field;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeWGS84Field, value) != true)) {
                    this.LatitudeWGS84Field = value;
                    this.RaisePropertyChanged("LatitudeWGS84");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongitudeWGS84 {
            get {
                return this.LongitudeWGS84Field;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeWGS84Field, value) != true)) {
                    this.LongitudeWGS84Field = value;
                    this.RaisePropertyChanged("LongitudeWGS84");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SOD {
            get {
                return this.SODField;
            }
            set {
                if ((this.SODField.Equals(value) != true)) {
                    this.SODField = value;
                    this.RaisePropertyChanged("SOD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SOG {
            get {
                return this.SOGField;
            }
            set {
                if ((this.SOGField.Equals(value) != true)) {
                    this.SOGField = value;
                    this.RaisePropertyChanged("SOG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TerminalTimeStamp {
            get {
                return this.TerminalTimeStampField;
            }
            set {
                if ((this.TerminalTimeStampField.Equals(value) != true)) {
                    this.TerminalTimeStampField = value;
                    this.RaisePropertyChanged("TerminalTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/LRIT.ASP.Services")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultMessage {
            get {
                return this.ResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultMessageField, value) != true)) {
                    this.ResultMessageField = value;
                    this.RaisePropertyChanged("ResultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LRITDataService.IASPDataService")]
    public interface IASPDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASPDataService/AddPosition", ReplyAction="http://tempuri.org/IASPDataService/AddPositionResponse")]
        IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Response AddPosition(IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Position position, string shipbornEquipmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IASPDataService/AddPosition", ReplyAction="http://tempuri.org/IASPDataService/AddPositionResponse")]
        System.Threading.Tasks.Task<IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Response> AddPositionAsync(IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Position position, string shipbornEquipmentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IASPDataServiceChannel : IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.IASPDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASPDataServiceClient : System.ServiceModel.ClientBase<IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.IASPDataService>, IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.IASPDataService {
        
        public ASPDataServiceClient() {
        }
        
        public ASPDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASPDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Response AddPosition(IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Position position, string shipbornEquipmentId) {
            return base.Channel.AddPosition(position, shipbornEquipmentId);
        }
        
        public System.Threading.Tasks.Task<IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Response> AddPositionAsync(IRIDIUM_GMDSS_LRIT.Forwarder.LRIT.LRITDataService.Position position, string shipbornEquipmentId) {
            return base.Channel.AddPositionAsync(position, shipbornEquipmentId);
        }
    }
}
